project_id = "dljhyagvkpwyprsslftp"

[functions.send-invitation-email]
verify_jwt = true

[functions.get-user-emails]
verify_jwt = true

[functions.add-user-with-invite]
verify_jwt = true

[functions.webhooks-inbound]
verify_jwt = false

[functions.webhooks-dispatcher]
verify_jwt = true

[functions.webhook-enqueue]
verify_jwt = true

[functions.api-tasks]
verify_jwt = false
